# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: "postgis/postgis:13-3.1-alpine"
    restart: always
    environment:
      POSTGRES_USER: training
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - 5432:5432
    volumes:
      - ./migrations/sql/:/docker-entrypoint-initdb.d/
